version: '2'
services:
  db_camunda:
    image: postgres:9.6
    hostname: postgres-camunda
    container_name: postgres-camunda
    restart: always
    environment:
      PGDATA: $BPM_DB_PATH/camunda
      POSTGRES_DB: $BPM_DB_NAME
      POSTGRES_USER: $BPM_DB_USER
      POSTGRES_PASSWORD: $BPM_DB_PASSWORD
      TZ: Europe/Moscow
    volumes:
      - ./data/camunda/postgresql:$BPM_DB_PATH
    ports:
      - $BPM_DB_PORT:5432
    networks:
      - custom_network
  db_homs:
    image: postgres:11.0
    hostname: postgres-homs
    container_name: postgres-homs
    restart: always
    environment:
      PGDATA: $HOMS_DB_PATH/homs
      POSTGRES_DB: $HOMS_DB_NAME
      POSTGRES_USER: $HOMS_DB_USER
      POSTGRES_PASSWORD: $HOMS_DB_PASSWORD
      TZ: Europe/Moscow
    volumes:
      - ./data/homs/postgresql:$HOMS_DB_PATH
    ports:
      - $HOMS_DB_PORT:5432
    networks:
      - custom_network
  camunda:
    image: latera/camunda
    container_name: camunda
    env_file:
      - ".env"
    links:
      - db_camunda:$BPM_DB_HOST
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_URL: "jdbc:postgresql://db_camunda:5432/$BPM_DB_NAME"
      DB_USERNAME: $BPM_DB_USER
      DB_PASSWORD: $BPM_DB_PASSWORD
      WAIT_FOR: "db_camunda:5432"
    ports:
      - $BPM_PORT:8080
    depends_on:
      - db_camunda
    networks:
      - custom_network
  minio:
    image: minio/minio
    container_name: minio
    command: "server /opt/minio"
    restart: always
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    volumes:
      - ./data/minio:/opt/minio
    ports:
      - $MINIO_PORT:9000
  memcached:
    image: memcached
    container_name: memcached
    hostname: memcached
    networks:
      - custom_network
networks:
  custom_network:
    driver: bridge
