locale:
  code: en
  datetime_format: '%m/%d/%Y %H:%M %p'

sessions:
  token_authentication:
    enabled: false
    token: null
    sign_in_as: user@example.com

link_to_manual: "http://hydra-oms.com/docs"

use_imprint: true

greeting:

announcement:

orders_expiration_warning_days: 1

base_url: '/'
